breeam/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/logout/$', 'django.contrib.auth.views.logout', {'next_page': 'pages.views.index'}),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'pages.views.index'),
    url(r'^macro-friendly/(?P<slug>[^\.]+)/$', 'pages.views.macro_friendly_slide'),
    url(r'^timeline/(?P<start>\d+)/(?P<end>\d+)/$', 'pages.views.timeline'),
    url(r'^macro/(?P<start>\d+)/(?P<end>\d+)/$', 'pages.views.macro'),
    url(r'^pages/(?P<slug>[^\.]+)/buttons', 'pages.views.show_buttons'),
    url(r'^pages/(?P<slug>[^\.]+)/json', 'pages.views.slide_json'),
    url(r'^pages/(?P<slug>[^\.]+)/$', 'pages.views.show_slide'),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
]

pages/models.py
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey

# Create your models here.


class Value(models.Model):
    interval = models.IntegerField(blank=True, null=True)
    macro_column_value = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return str(self.interval)


class Setting(models.Model):
    name = models.CharField(max_length=70, blank=True, null=True)
    site_name = models.CharField(max_length=255, blank=True, null=True)
    site_title = models.CharField(max_length=255, blank=True, null=True)
    timeline_and_macro_objects = models.ForeignKey(Value, null=True, default=1)

    def __str__(self):
        return self.name


class Template(models.Model):
    name = models.CharField(max_length=70, blank=True, null=True)
    file_name = models.CharField(max_length=100, blank=True, null=True)
    headers = models.IntegerField(blank=True, null=True, default=0)
    images = models.IntegerField(blank=True, null=True, default=1)

    def __str__(self):
        return self.name


class Decor(models.Model):
    name = models.CharField(max_length=200, blank=True, null=True)
    top_image_1 = models.FileField(upload_to='images/decor/')
    top_image_2 = models.FileField(upload_to='images/decor/')
    top_image_3 = models.FileField(upload_to='images/decor/')
    bottom_image_1 = models.FileField(upload_to='images/decor/')
    bottom_image_2 = models.FileField(upload_to='images/decor/')

    def __str__(self):
        return self.name


class Slide(MPTTModel):
    title = models.CharField(max_length=70, unique=True, null=False)
    center = models.BooleanField(default=False, blank=True)
    align_title_in_image = models.BooleanField(default=False, blank=True)
    slug = models.SlugField(unique=True) #Used to access slides and if url is needed then it will be used to give a SEO friendly URL
    decor = models.ForeignKey(Decor, null=True, blank=True, default=1)
    template = models.ForeignKey(Template, null=True, default=1)
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children', db_index=True)

    def __str__(self):
        return self.title


class SlideButton(models.Model):
    slide = models.ForeignKey(Slide)
    name = models.CharField(max_length=40, unique=False)
    url = models.URLField(max_length=100, unique=False)


class SlideHeader(models.Model):
    slide = models.ForeignKey(Slide)
    header = models.CharField(max_length=50, unique=False)
    url = models.URLField(blank=True) # If header should have a link to it

    class Meta:
        ordering = ['pk']


class SlideImage(models.Model):
    slide = models.ForeignKey(Slide)
    image = models.FileField(upload_to='images/slide_images/', default='images/slide_images/default.jpg')
    description = models.TextField(blank=True) # For alt text
    url = models.URLField(blank=True) # If image should have a link to it

    class Meta:
        ordering = ['pk']

pages/templates/index.html
{% extends 'layouts/layout.html' %}
{% load staticfiles %}
{% block title %}<title>{{ site_title }}</title>{% endblock title %}
{% block content %}

<!-- Main content, including slider, timeline and page buttons. -->
<div class="mainContent">

    <!-- Header with decor items -->
    <header>
        <div>
            <img src="{{ slide.decor.top_image_1.url }}">
        </div>
        <div>
            <img src="{{ slide.decor.top_image_2.url }}">
        </div>
        <div>
            <img src="{{ slide.decor.top_image_3.url }}">
        </div>
    </header>
    
	<div id="warning-message">
        <h2>This website does not support portrait mode</h2>
    	<img src=" {% static 'images/cellphoneTilt.png' %}" />
    </div>

    <div id="magnifier">
		<div class="magnifier-icon">
        	<span class="magnifier-handle"></span>
        	<span class="magnifier-handle-x"></span>
		</div>
    </div>

	<a class="logo" href="/">{{ site_name }}</a>
    <!-- Link for admin -->
    <a class="loginBtn" href="{% url 'admin:login' %}">Sign in</a>
    
    <div class="mainWrapper" id="wrapper">

        <!-- Slide title -->
        {% block slide-title %}
            <div class="{{ slide.align_title_in_image|yesno:"pageTitleFloat,pageTitleStandard" }} {{ slide.center|yesno:"pageTitleCenter," }}" id="page_title">
                <h1 id="headline">{{ slide.title }}</h1>
            </div>
        {% endblock slide-title %}

        <!-- Slide content -->
        <div class="content-container">
            <!-- Link for the next slide -->
            <a href="#" class="arrow-left" id="prev_slide">
                  <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <!-- Link for the next slide -->
            <a href="#" class="arrow-right" id="next_slide">
                  <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
            <div class="slider-content" id="slider">
                <!-- Load content with jQuery -->
            </div>
        </div>

        <!-- Loader -->
        {% block loader %}
            <div class="loader" id="loader">
              <svg class="circular">
                <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10"/>
              </svg>
            </div>
        {% endblock loader %}

        <!-- Timeline -->
        {% block timeline %}
            <div class="timelineContainer">
                <div class="pagination" id="timeline">
                    {% include 'includes/timeline.html' %}
                </div>
            </div> <!-- timelineContainer -->
        {% endblock timeline %}

        <!-- Slide buttons -->
        <div class="navButtons" id="buttons">
            <div class="btn-group">
	            <ul class="nav-pills">
    	            {% for button in slide.slidebutton_set.all %}
        	            <li><a href="{{ button.url }}" class="btn btn-primary btn-lg" role="button">{{ button.name }}</a></li>
                    {% endfor %}
	            </ul>
            </div>
        </div>
    </div> <!-- mainWrapper -->

    <div id="macro_wrapper">
    </div> <!-- macroWrapper -->

    <!-- Macro navigation -->
    <div class="row text-center" id="macro_menu">
    	<a href="javascript:void(0)" id="macro_prev" class="arrow-left">
        	<span class="glyphicon glyphicon-chevron-left"></span>
        </a>
		<a href="javascript:void(0)"id="macro_next" class="arrow-right">
        	<span class="glyphicon glyphicon-chevron-right"></span>
        </a>

        {% include 'includes/macro_timeline.html' %}
    </div>

    <!-- Footer with decor items -->
    <footer>
        <div>
            <img src="{{ slide.decor.bottom_image_1.url }}">
        </div>
        <div>
            <img src="{{ slide.decor.bottom_image_2.url }}">
        </div>
    </footer>    

</div> <!-- mainContent -->
<script type="text/javascript">
    //Set global variables
    interval = {{ interval }};
    macro_views = {{ macro_views }};

    /*
    var start = interval + 1;
    var end = interval*2 + 1;
    var timeline = $('div#timeline');
    //Initiate startup time line
    //Done in django view
    //Update time line
    $('div#timeline a:last-child').on('click', function () {
        //Get elements data
        $.getJSON('/timeline/' + start + '/' + end, function (data) {
            //Check if more elements exist

            //

        });

        //Load new elements

    });*/
</script>

{% endblock content %}

pages/templates/macro.html
<div class="row">
    {% for slide in slides %}
        <div class="col-xs-{{ column_value }} text-center macroLinks">
        	<a href="{{ slide.slug }}" class="macroTooltip"><p>{{ slide.title }}</p>
                <a href="{{ slide.slug }}" class="macro_content macro_url">
                </a>
            </a>
        </div>
    {% endfor %}
</div>