breeam/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/logout/$', 'django.contrib.auth.views.logout', {'next_page': 'pages.views.index'}),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', 'pages.views.index'),
    url(r'^macro-friendly/(?P<slug>[^\.]+)/$', 'pages.views.macro_friendly_slide'),
    url(r'^timeline/(?P<start>\d+)/(?P<end>\d+)/$', 'pages.views.timeline'),
    url(r'^macro/(?P<start>\d+)/(?P<end>\d+)/$', 'pages.views.macro'),
    url(r'^pages/(?P<slug>[^\.]+)/buttons', 'pages.views.show_buttons'),
    url(r'^pages/(?P<slug>[^\.]+)/json', 'pages.views.slide_json'),
    url(r'^pages/(?P<slug>[^\.]+)/$', 'pages.views.show_slide'),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
]

pages/models.py
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey

# Create your models here.


class Value(models.Model):
    interval = models.IntegerField(blank=True, null=True)
    macro_column_value = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return str(self.interval)


class Setting(models.Model):
    name = models.CharField(max_length=70, blank=True, null=True)
    site_name = models.CharField(max_length=255, blank=True, null=True)
    site_title = models.CharField(max_length=255, blank=True, null=True)
    timeline_and_macro_objects = models.ForeignKey(Value, null=True, default=1)

    def __str__(self):
        return self.name


class Template(models.Model):
    name = models.CharField(max_length=70, blank=True, null=True)
    file_name = models.CharField(max_length=100, blank=True, null=True)
    headers = models.IntegerField(blank=True, null=True, default=0)
    images = models.IntegerField(blank=True, null=True, default=1)

    def __str__(self):
        return self.name


class Decor(models.Model):
    name = models.CharField(max_length=200, blank=True, null=True)
    top_image_1 = models.FileField(upload_to='images/decor/')
    top_image_2 = models.FileField(upload_to='images/decor/')
    top_image_3 = models.FileField(upload_to='images/decor/')
    bottom_image_1 = models.FileField(upload_to='images/decor/')
    bottom_image_2 = models.FileField(upload_to='images/decor/')

    def __str__(self):
        return self.name


class Slide(MPTTModel):
    title = models.CharField(max_length=70, unique=True, null=False)
    center = models.BooleanField(default=False, blank=True)
    align_title_in_image = models.BooleanField(default=False, blank=True)
    slug = models.SlugField(unique=True) #Used to access slides and if url is needed then it will be used to give a SEO friendly URL
    decor = models.ForeignKey(Decor, null=True, blank=True, default=1)
    template = models.ForeignKey(Template, null=True, default=1)
    parent = TreeForeignKey('self', null=True, blank=True, related_name='children', db_index=True)

    def __str__(self):
        return self.title


class SlideButton(models.Model):
    slide = models.ForeignKey(Slide)
    name = models.CharField(max_length=40, unique=False)
    url = models.URLField(max_length=100, unique=False)


class SlideHeader(models.Model):
    slide = models.ForeignKey(Slide)
    header = models.CharField(max_length=50, unique=False)
    url = models.URLField(blank=True) # If header should have a link to it

    class Meta:
        ordering = ['pk']


class SlideImage(models.Model):
    slide = models.ForeignKey(Slide)
    image = models.FileField(upload_to='images/slide_images/', default='images/slide_images/default.jpg')
    description = models.TextField(blank=True) # For alt text
    url = models.URLField(blank=True) # If image should have a link to it

    class Meta:
        ordering = ['pk']

pages/templates/slider_layouts/quad.html
<div id="holder">
    {% include 'includes/title.html' %}
    <div class="slider-content" id="slider">
        <div class="row quadRow1 text-center">
            <div class="row container-fluid text-center quadImgs">
                {% for image in slide.slideimage_set.all|slice:":2" %}
                    <div class="col-xs-6">
                        <a href="{{ image.url }}">
                            <img class="img-responsive" src="{{ image.image.url }}" alt="{{ image.description }}" />
                        </a>
                    </div>
                {% endfor %}
            </div>
            <div class="row container-fluid text-center quadImgTxt">
                {% for header in slide.slideheader_set.all|slice:":2" %}
                    <div class="col-xs-6">
                        <a href="{{ header.url }}" >{{ header.header }}</a>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="row quadRow2 text-center">
            <div class="row container-fluid text-center quadImgs">
                {% for image in slide.slideimage_set.all|slice:"2:4" %}
                    <div class="col-xs-6">
                        <a href="{{ image.url }}">
                            <img class="img-responsive" src="{{ image.image.url }}" alt="{{ image.description }}" />
                        </a>
                    </div>
                {% endfor %}
            </div>
            <div class="row container-fluid text-center quadImgTxt">
                {% for header in slide.slideheader_set.all|slice:"2:4" %}
                    <div class="col-xs-6">
                        <a href="{{ header.url }}" >{{ header.header }}</a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    {% include 'includes/decor.html' %}
    <div id="buttons">
        {% include 'includes/buttons.html' %}
    </div>
</div>

pages/templates/slider_layouts/standard.html
<div id="holder">
    {% include 'includes/title.html' %}
    <div class="slider-content" id="slider">
        {% for image in slide.slideimage_set.all|slice:":1" %}
            <!-- Current Slide Image -->
            <img src="{{ image.image.url }}" alt="{{ image.description }}" />
        {% endfor %}
    </div>
    {% include 'includes/decor.html' %}
    <div id="buttons">
        {% include 'includes/buttons.html' %}
    </div>
</div>

pages/templates/slider_layouts/triple.html
<div id="holder">
    {% include 'includes/title.html' %}
    <div class="slider-content" id="slider">
        <!-- Current Slide Image -->
        <div class="row container-fluid text-center trippleImgTxt">
            {% for header in slide.slideheader_set.all|slice:":3" %}
                <div class="col-xs-4">
                    <a href="{{ header.url }}" target="_blank" >{{ header.header }}</a>
                </div>
            {% endfor %}
        </div>
        <div class="row container-fluid text-center trippleImgs">
            {% for image in slide.slideimage_set.all|slice:":3" %}
                <div class="col-xs-4">
                    <a href="{{ image.url }}" target="_blank">
                        <img class="img-responsive" src="{{ image.image.url }}" alt="{{ image.description }}" />
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
    {% include 'includes/decor.html' %}
    <div id="buttons">
        {% include 'includes/buttons.html' %}
    </div>
</div>